---
version: '3.4'
services:

  datascience:
    build: 
      context: ./src 
    image: chinkitp/all-spark-notebook:latest
    ports:
      - "8888:8888"    
    volumes:
      - ./src/work:/home/jovyan/work
      - ./../../../../../04-BigData/bitcoin-blocks/:/bitcoin-blocks/
    