- hosts: digitalocean
  # roles:
  #   - digitalocean
  vars : 
    do_token: !vault |
          $ANSIBLE_VAULT;1.2;AES256;dev
          66353539343933396263663030373730336466366539313866346461343533633339613739356465
          6365323336306431636262663333653433393939663265620a656337633065376537333261656630
          64346136356164643164313930383733356537613838623031316264656231613731663934616564
          3139656437623762310a363231623564626632366530646362383262383364323630633161613331
          37653735366432613635336166363835353839363531643139616139656431623431343662336365
          32613162636532343565643663386364396434633239333634336636393166353538313138383466
          34313432666230666362616136646332303236363463363130346265393564626632353864643935
          64343535623434343839
    droplets:
    - droplet-one
    - droplet-two 
    es_major_version: "2.x"
    es_version: "2.2.1"
    es_heap_size: "2g"
    es_cluster_name: "production"

  tasks:

          
  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=my_ssh_key
      ssh_pub_key={{ lookup('file', '../.ssh/id_rsa.pub') }}
      api_token={{ do_token }}
    register: my_ssh_key


  - name: ensure droplets exist
    digital_ocean: >
      state=present
      command=droplet
      name={{ item }}
      unique_name=yes
      size_id=512mb
      private_networking=yes
      region_id=sgp1
      image_id=ubuntu-16-04-x64
      ssh_key_ids={{ my_ssh_key.ssh_key.id }}
      api_token={{ do_token }}
    with_items: "{{droplets}}"
    register: droplet_details

  - name: Add new host to our inventory.
    add_host:
      name: "{{ item }}"
      groups: do
    with_items:
     - "{{ droplet_details.results|map(attribute='droplet.ip_address')|list }}"

  - debug: 
      msg="IP is {{ item }}"
    with_items:
     - "{{ droplet_details.results|map(attribute='droplet.ip_address')|list }}"

- hosts: do
  remote_user: root
  gather_facts: False
    
  tasks:
    - name: Wait for port 22 to become available.
      local_action: "wait_for port=22 host={{ inventory_hostname }}"  

    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest

    - name: Add Oracle Java Repository
      become: yes
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      become: yes
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default
